name: New CBV
description: File a new vulnerability to CBV database
title: "[Submit: ]: "
labels: ["CBV"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing with this project!
  # title.header
  - type: input
    id: header
    attributes:
      label: Title
      description: Introduce vulnerability Title
      placeholder: Your proposed title
    validations:
      required: true
  # title.description
  - type: textarea
    id: description
    attributes:
      label: Short description
      description: Please enter a summary of the vulnerability
      placeholder: Here you should place a brief description of the vulnerability
    validations:
      required: true
  # blockchain
  - type: dropdown
    id: blockchain
    attributes:
      label: Blockchain
      description: What blockchain is been affected by this vulnerability?
      multiple: true
      options:
        - Bitcoin
        - Ethereum
        - Polygon
        - Polkadot
    validations:
      required: true
  # version_affected
  - type: textarea
    id: version_affected
    attributes:
      label: Version affected
      description: Wich version of the blockchain is been affected by this vulnerability?
      placeholder: Bitcoin Core 0.14.x before 0.14.3, 0.15.x before 0.15.2, and 0.16.x before 0.16.3 and Bitcoin Knots 0.14.x through 0.16.x before 0.16.3
    validations:
      required: true
  #
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  # details
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
   
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
