name: Store new CBV in DB

on:
  issues:
    types: [closed]

jobs:
  update-CBV-index:
# labels includes [Accepted] ? store DB and upload new .md file : break without commit
    if: contains(${{github.event.issue.labels.*.name}},"Accepted")
    name: folder scan
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.29.1"

      - name: Deno run
        id: deno
        run: deno run --allow-write --allow-read --allow-env .github/scripts/mod.ts "${{ github.event.issue.body }}" ${{ secrets.v1_api_graphql }} > $GITHUB_OUTPUT

      - name: echo
        run: echo ${{join(steps.deno.outputs.*, '\n')}}

# todo: revisar como pasar la informacion de un step al otro.
      - name: Commit files
        #env: 
        #  COMMIT_NAME: ${{steps.deno.outputs}}
        run: .github/scripts/commit.sh
      
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: main
